#Importacion de las librerias necesarias
library(readxl)
library(dplyr)
library(stringr)

#referenciando el directorio de trabajo
setwd(dirname(rstudioapi::getSourceEditorContext()$path))

#Lectura de datos
data_1519 <- read_excel( "b1519_renap.xlsx")
data_1921 <- read_excel("baseCES2021_renap.xlsx")

#Obteniendo los valores unicos presentados en la columna de departamento
unique(data_1519$DEPARTAMENTO)

#Filtrando los registros que tienen departamentos de Guatemala
departamentos_validos <- c("BAJA VERAPAZ", "HUEHUETENANGO","GUATEMALA", "ALTA VERAPAZ",
                           "CHIQUIMULA", "QUICHE", "QUETZALTENANGO", "ESCUINTLA", "ZACAPA",
                           "IZABAL", "SAN MARCOS", "TOTONICAPAN", "JUTIAPA", "SACATEPEQUEZ",
                           "PETEN", "RETALHULEU", "SUCHITEPEQUEZ", "SANTA ROSA", "SOLOL�",
                           "CHIMALTENANGO", "EL PROGRESO", "JALAPA")

data_1519 <- subset(data_1519, DEPARTAMENTO %in% departamentos_validos)
unique(data_1519$DEPARTAMENTO)

#Verificando los valores unicos de las demas columnas
unique(data_1519$SEXO)
data_1519$SEXO[data_1519$SEXO == "I"] ="DESCONOCIDO"
unique(data_1519$EDAD)
data_1519$EDAD[is.na(data_1519$EDAD)] = "DESCONOCIDA"

unique(data_1519$CAUSA1)
unique(data_1519$CAUSA2)
unique(data_1519$CAUSA3)
unique(data_1519$CAUSA4)
unique(data_1519$FECHA)
data_1519 <- data_1519[,-3]

#Eliminando columnas y modificando nombres para hacer coincidir bases de datos 
data_1921
data_1921 <- data_1921[,c(-12,-5,-3)]
names(data_1921)
names (data_1921)[4] = "SEXO"
names (data_1921)[3] = "DEPARTAMENTO"
names (data_1921)[1] = "ID"
names (data_1921)[6] = "CAUSA1"
names (data_1921)[7] = "CAUSA2"
names (data_1921)[8] = "CAUSA3"
names (data_1921)[9] = "CAUSA4"

unique(data_1921$DEPARTAMENTO)
data_1921 <- subset(data_1921, DEPARTAMENTO %in% departamentos_validos)

#Cambiando los valores faltantes por "DESCONOCIDOS"
unique(data_1921$SEXO)
data_1921$SEXO[is.na(data_1921$SEXO)] = "DESCONOCIDO"

unique(data_1921$EDAD)
data_1921$EDAD[is.na(data_1921$EDAD)] = "DESCONOCIDA"

data_1921 <- data_1921 %>% filter(FECHA >= "2015-01-01")

#merge de las bases de datos
all_data <- merge(data_1519, data_1921, all = TRUE)

all_data$ID <- seq.int(nrow(all_data))
all_data <- all_data[,c("ID", names(all_data)[names(all_data) != "ID"])]

all_data[['FECHA']] <- strptime(all_data[['FECHA']], format = "%Y-%m-%d")



unique(all_data$EDAD)
unique(all_data$SEXO)
unique(all_data$FECHA)
all_data$CAUSA1[is.na(all_data$CAUSA1)] = "DESCONOCIDA"
all_data$CAUSA1[all_data$CAUSA1=='"Ignorado'] = "DESCONOCIDA"
all_data$CAUSA1[all_data$CAUSA1=='"Ignorado"'] = "DESCONOCIDA"
all_data$CAUSA1[all_data$CAUSA1=='"ignorado"'] = "DESCONOCIDA"
all_data$CAUSA1<- str_replace_all(all_data$CAUSA1, "^-", "DESCONOCIDA")
all_data$CAUSA1<- str_replace_all(all_data$CAUSA1, "^\\s", "DESCONOCIDA")
all_data$CAUSA2[is.na(all_data$CAUSA2)] = "DESCONOCIDA"
all_data$CAUSA3[is.na(all_data$CAUSA3)] = "DESCONOCIDA"
all_data$CAUSA4[is.na(all_data$CAUSA4)] = "DESCONOCIDA"
all_data$EDAD[is.na(all_data$EDAD)] = "DESCONOCIDA"

all_data$CAUSA1[all_data$CAUSA1=='Paro Cardio Respiratorio'] = "Paro Cardiorrespiratorio"
all_data$CAUSA1[all_data$CAUSA1=='Paro Cardiorespiratorio'] = "Paro Cardiorrespiratorio"
#Segun la literatura consultado un paro cardiaco y un paro cardiorrespiratorio son lo mismo
all_data$CAUSA1[all_data$CAUSA1=='Paro Cardiaco'] = "Paro Cardiorrespiratorio"
all_data$CAUSA1[all_data$CAUSA1=='Infarto Agudo del Miocardio'] = "Infarto Agudo al Miocardio"
all_data$CAUSA1[all_data$CAUSA1=='Neumonua'] = "Neumon�a"
all_data$CAUSA1[all_data$CAUSA1=='Neumonia'] = "Neumon�a"
all_data$CAUSA1[all_data$CAUSA1=='Choque Septico'] = "Choque S�ptico"
all_data$CAUSA1[all_data$CAUSA1=='Choque Suptico'] = "Choque S�ptico"

all_data$CAUSA1<-str_replace_all(all_data$CAUSA1, "_", "")
all_data$CAUSA1<-str_replace_all(all_data$CAUSA1,"1", "")
all_data$CAUSA1<-str_replace_all(all_data$CAUSA1,"-", "")
all_data$CAUSA1<-str_replace_all(all_data$CAUSA1,"Causa directa:", "")
all_data$CAUSA1<-str_replace_all(all_data$CAUSA1,"causa directa:", "")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"  Choque Septico Pulmonar", "Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"  Choque Septico pulmonar,", "Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Choque S�ptico", "Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Choque Septico","Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Choque Septico  Abdominal  Absceso + Bridas y Adherencia","Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Choque Septico    Sepsis IntraAbdominal    Gastrointeritis Aguda   Peritonitis Severa","Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Choque Septico  Infeccion Tejidos Blandos","Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Choque Septico  Neumonia Aspirativa","Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Choque Septico  Origen Abdominal","Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Choque Septico A Infeccion tejido Blando","Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Choque Septico A Infecci�n del Tracto Urinario","Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Choque Septico de Pulmon","Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Choque Septico Foco Intra abdominal","Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Choque Septico refractario a aminas   a Neumonia Aspirativa","Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Choque s�ptico pulmonar y tejidos blandos","Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"  Bronco Neumon�a Bilateral", "Bronconeumonia bilateral")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"bronconeumon�a bilateral", "Bronconeumonia bilateral")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "	. Causa Directa: ","")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Dengue hemorr�gico", "Dengue hemorragico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "ICC", "Insuficiencia cardiaca congestiva")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, " S�psis del Recien Nacido", "Sepsis del recien nacido")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Alteraci�n del Estado de Conciencia ", "Alteracion del estado de conciencia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "CA DE ESTOMAGO", "Cancer Gastrico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"CA cervix estudio estudio 3B metastasis","Cancer de cervix")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Choque neurog�nico refractorio a aminas", "Choque neurogenico refractorio a aminas")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Cirrosis hep�tica", "Cirrosis hepatica")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, " Causa Directa: ", "")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Choque Septico pulmonar,", "Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "COMA DIABETICO", "Coma diabetico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Coma Diab�tico", "Coma diabetico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "C�ncer de mama diseminado grado IV.","Cancer de mama diseminado")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "ECN hemorr�gico", "Evento cerebrovascular hemorragico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, " Estado de Choque", "Estado de choque")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Estado de choque Hipovolemico", "Choque hipovolemico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Estado de Choque Hipovol�mico", "Choque hipovolemico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Estado de Choque Septico,", "Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Estado de choque septico. NAC,", "Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Estado de choque septico. NAC,", "Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Infecci�n Gastrointestinal", "Infeccion gastrointestinal")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Infarto del Miocardio ", "Infarto al miocardio")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "infarto del miocardio ", "Infarto al miocardio")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Shock Septico","Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Choque Septico","Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Neumon�a", "Neumonia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Senilidad", "Senectud")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "	Paro cardiorespiratorio", "Paro Cardiorrespiratorio")
all_data$CAUSA1<-gsub('[0-9]*','',all_data$CAUSA1)
all_data$CAUSA1<-gsub("\\.","", all_data$CAUSA1)
all_data$CAUSA1<-gsub("a)", "", all_data$CAUSA1)
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Alcoholismo nivel de intoxicaci�n no especificada","Alchoholismo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Alcoholismo nivel de intoxicaci�n no espeficada","Alcoholismo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Alcoholismo nivel de intoxicaci�n, no especificado","Alcoholismo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Alcoholismo, nivel de intoxicaci�n no especificada","Alcoholismo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Alcoholismo, nivel de Intoxicaci�n no especificada","Alcoholismo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Alcoholismo, Nivel de Intoxicaci�n no especificada","Alcoholismo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Alcoholismo, nivel de intoxicaci�n no especificado","Alcoholismo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Alcoholismo, nivel de intoxicaci�n, no especificada","Alcoholismo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Alcoholismo, nivel de Intoxicaci�n, no especificado","Alcoholismo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Alcohol�smo Cr�nico","Alcoholismo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Alcoh�lismo Cr�nica","Alcoholismo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "alcoholismo Agudo","Alcoholismo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Alcoholismo Cronico","Alcoholismo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Alcoholismo Cr�nico","Alcoholismo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Alchoholismo","Alcoholismo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, " Accidente vascular encefalico","Evento Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, " Accidente Vascular encefalico","Evento Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Accidente vascular encef�tico agudo no especificado como hemorragico o esqu�mico", "Evento Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Bronco Neumonia Neumonia", "Bronconeumonia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Bronconeumonia Neumonia","Bronconeumonia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Bronconeumonia Neumonia", "Bronconeumonia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Bronconeumonia no especificada", "Bronconeumonia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Bronconeumon�a","Bronconeumonia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Bronconeumon�a Neumonia", "Bronconeumonia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"	Bronconeumon�a Neumonia","Bronconeumonia")
all_data$CAUSA1<-str_trim(all_data$CAUSA1, side = "both")
all_data$CAUSA1<-gsub("\\,", "", all_data$CAUSA1)
all_data$CAUSA1<-gsub("\\:", "", all_data$CAUSA1)
all_data$CAUSA1<-gsub("\\;","", all_data$CAUSA1)
all_data$CAUSA1<-gsub(";;","", all_data$CAUSA1)
all_data$CAUSA1<-gsub(")","", all_data$CAUSA1)
all_data$CAUSA1<-gsub("\\(","",all_data$CAUSA1)
all_data$CAUSA1<-gsub("]","", all_data$CAUSA1)
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Cirrosis Hep�tica", "Cirrosis Hepatica")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Paro cardiorespiratorio", "Paro Cardiorrespiratorio")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Paro Cardio respiratorio", "Paro Cardiorrespiratorio")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Paro cardio respiratorio", "Paro Cardiorrespiratorio")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Paro Cardiorespiratorio", "Paro Cardiorrespiratorio")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Paro CardioRespiratorio", "Paro Cardiorrespiratorio")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Enfermedad Com�n", "Enfermedad Comun")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Choque septico", "Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Shock S�ptico", "Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Shock septico", "Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Shock Hipovolemico", "Choque Hipovolemico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Insuficiencia Renal Cr�nica", "Insuficiencia Renal Cronica")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Choque septico", "Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Evento Cerebro Vascular", "Evento Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Infarto Agudo Miocardio", "Infarto Agudo al Miocardio")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Infarto al Miocardio", "Infarto Agudo al Miocardio")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Shock Hipovol�mico", "Choque Hipovolemico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Choque Hipovol�mico", "Choque Hipovolemico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "INFARTO AGUDO AL MIOCARDIO", "Infarto Agudo Al Miocardio")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Fallo Ventilatorio", "Falla Ventilatoria")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Falla Multiorganica", "Fallo Multiorganico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Accidente Cerebro Vascular", "Evento Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Senelidad", "Senectud")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Fallo Multiorg�nico", "Fallo Multiorganico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Fallo Multisistemico", "Fallo Multiorganico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Choque Hipovol�mico","Choque Hipovolemico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y gastroenteritis de presunto origen infeccioso + DHE grado III","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenteritis de presunto origen infecioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenteritis de Presunto origen inteso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroentercolitis del presunto origen infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y gastroenteritis","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Gastroenterocolitis de Presunto Origen Infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenteritis de presuno origen infeccios","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y gastroenteritis de presunto origen infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y gastroenteritis de presunto origen infecci�n","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y gastroenteritis de presunto origen infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y gastroenteritis de Presunto Origen Infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenteritis de presunto origen infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenteritis de Presunto origen infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenteritis de Presunto Origen Infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y gastroenteritis de presutno origen infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenteritis del presunto origen infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenteritis del Presunto origen infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenteritis del Presunto origen Infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenteritis del Presunto Origen Infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea Y Gastroenteritis del presunto origen infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenterocolitis de presunto origen infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenterocolitis del presunto origen infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroentritis de presunto origen infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastrointeritis de presunto origen infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gatroenteritis de Presunto Origen Infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Diarea y gastroenteritis","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Diarrea","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Diarrea y gastroenteritis","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Diarrea y Gastroenteritis","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Diarrea y gastroenteritis de origen infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Diarrea y gastroenteris de presunto origen infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Diarrea y gastroenteritis","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Diarrea y Gastroenteritis de Presunto Origen Infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Diarrea Y Gastroenteritis de presunto origen infeccioso","Gastroenterocolitis infecciosa")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Infecci�n Intestinal Bacteria no especificada","Infeccion intestinal no especificada")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  septicemia no especificada","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Septicem�a no especificada","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A    septicemia","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A    Septicemia","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A    septicemia no especificada","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A    Septicemia no especificada","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A   Septicemia","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A   Septicemia no espec�ficada","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Sepsis Neotal","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Septicemia","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  septicemia no especificada","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Septicemia no especificada","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Septicemia no especificada Choque Septico","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Septicemia no especificado","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Septicemia no espec�ficada","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Septicem�a no especificada","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Septicemia","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  septicemia no especificada","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Septicemia no especificada","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Septicemia no especificada Choque Septico","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Septicemia no especificado","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Septicemia no espec�ficada","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Septicem�a no especificada","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Sepsis Neotal","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  septicemia no especificada","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Septicem�a no especificada","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  septicemia no especificada","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Septicem�a no especificada","Septicemia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C V","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C V  accidente cerebro Vascular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C V  Hemorragico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C V Accidente Cerebral Vascular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C V Fulminante","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C V Hemorracico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C V Hemorragico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C V III IV","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C V Isquemico Agudo","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C X","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C V","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C V  accidente cerebro Vascular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C V  Hemorragico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C V Accidente Cerebral Vascular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A ACCIDENTE CEREBRO VASCULAR","Accidente cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C V Fulminante","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C V Hemorracico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C V Hemorragico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C V III IV","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C V Isquemico Agudo","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A C X","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A CAUSA DE","")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A causa de","")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Completar con estudio","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A completar por estudios adicionales","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A COMPLETAR POR ESTUDIOSADICIONALES","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A de Terminar","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Descartar Cardiopatia Ventricular Unico","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A descartar Masa Cerebral","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Deteminar","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Determinan Por Estudios Complementarios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"a determinar","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"a Determinar","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Determinar","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A DETERMINAR","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar con estudio","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar en estudio","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Determinar en Estudio","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Determinar En Estudio","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar en Peritajes complementarios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Determinar en Peritajes Complementarios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A DETERMINAR EN PERITAJES COMPLEMENTARIOS","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar en peritajes complementarios causa no determinada en estudio","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar intoxicaci�n","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar mediante estudio histopatol�gico","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"a determinar plaguicidas y/o herbicidas","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A DETERMINAR POR ESTUDIOS COMPLEMENTARIOS","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar por estudio","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Determinar por estudio","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Determinar por Estudio Complementario","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar por estudios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar por Estudios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Determinar por estudios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Determinar por Estudios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Determinar por estudios Posteriores","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar por estudios complementario","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"a determinar por estudios complementarios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar por estudios complementarios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar por estudios Complementarios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Determinar por estudios complementarios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Determinar por estudios Complementarios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Determinar por Estudios Complementarios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Determinar por estudios Posteriores","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar por examenes complementarios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar por Laboratorios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Determinar por Peritaje","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar por Peritaje complementario","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar por Peritaje Complementario","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Determinar por peritaje complementario","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar por peritaje complementarios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Determinar por Peritaje Complementarios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar por peritajes complementarios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A determinar por peritajes complementarios posible ingestion de fosfuro de Aluminios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Determoinar","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  determinar por estudios complementarios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Estudio","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"a Diarrea","Diarrea")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea","Diarrea")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea  Gastro Enteritis de Presunto de Origen Infeccioso","Diarrea")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y gastroenteritis de presunto origen infeccioso + DHE grado III","Diarrea")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenteritis de presunto origen infecioso","Diarrea")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenteritis de Presunto origen inteso","Diarrea")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroentercolitis del presunto origen infeccioso","Diarrea")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y gastroenteritis","Diarrea")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenteritis de presuno origen infeccios","Diarrea")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y gastroenteritis de presunto origen infeccioso","Diarrea")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y gastroenteritis de presunto origen infecci�n","Diarrea")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y gastroenteritis de presunto origen infeccioso","Diarrea")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y gastroenteritis de Presunto Origen Infeccioso","Diarrea")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenteritis de presunto origen infeccioso","Diarrea")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenteritis de Presunto origen infeccioso","Diarrea")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenteritis de Presunto Origen Infeccioso","Diarrea")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y gastroenteritis de presutno origen infeccioso","Diarrea")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Diarrea y Gastroenteritis del presunto origen infeccioso","Diarrea")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A estidio","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Estudiar","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"a estudio","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A estudio","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Estudio","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A ESTUDIO","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Estudio DESCONOCIDA por Peritajes Complementarios","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A estudio Intoxicaci�n por Qu�mico","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A estudio parDESCONOCIDA","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A EN ESTUDIO","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Descartar Cardiopatia Ventricular Unico","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A DESCONOCIDA","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdome agudo","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdome Agudo","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Aguado","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Aguda","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"abdomen agudo","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen agudo","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"ABDOMEN AGUDO","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo Complicado","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo   R","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo  Shock septico","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo / Dolor Abdominal Severa","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo D/C Trombosis Mesenterica","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo de Efiologia","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo de Etiologia","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo dolor Abdominal Severo","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen agudo en estudio","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo en Estudio","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen agudo no especificado","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo no especificado","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo no especificado","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo no Especificado","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen agudo por obstrucci�n v�as biliares","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo Por Perforacion Intestinal","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo por Hernias Atascadas","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo Post quir�rgico Cierre de Colostom�a","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen agudo quirurgico","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo Quirurgico","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo Quir�rgico","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo Secundario a Perforaci�n Intestinal","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo Shock","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Agudo V�lvulo del sigmoides acidosis Respiratoria","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Aquido","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Dolor Cr�nico","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Hostil","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdomen Quirurgico Agudo","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdominal Agudo","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdom�n Agudo","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Abdonmen Agudo","Abdomen Agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Alteracion de la Conciencia","Alteracion de la conciencia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Alteraci�n de la Conciencia","Alteracion de la conciencia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Alteraci�n de la Conaenas","Alteracion de la conciencia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Alteraci�n de la conciencia","Alteracion de la conciencia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Alteraci�n de la Consiencia","Alteracion de la conciencia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Alteracion de la Conciencia","Alteracion de la conciencia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Alteraci�n de la Conciencia","Alteracion de la conciencia")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Choque Hipovolemico","Choque hipovolemico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Choque Hipovolemico Refractario","Choque hipovolemico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Choque Hipovolemico Secundario a","Choque hipovolemico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1," Choque Hipovulemico","Choque hipovolemico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Sindrome Diarreico Agudo","Sindrome diarreico agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Tuberculosis Pulmonar","Tuberculosis pulmonar")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A  Tuberculosis Respiratoria Confirmado","Tuberculosis pulmonar")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Acidosis mixta A Cetoacidosis A  Diabetes mellitus tipo ll","Cetoacidosis")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Ameboma Intestinal","Ameboma instestinal")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A ANOXIA CEREBRAL","Anoxia cerebral")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Infarto agudo al miocardio","Infarto Agudo al Miocardio")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Diabetes","Diabetes Mellitus")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Laceraci�n Cerebral","Laceracion Cerebral")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Infarto Agudo de Miocardio","Infarto Agudo al Miocardio")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Infarto Agudo Al Miocardio","Infarto Agudo al Miocardio")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"a Sepsis","Sepsis")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A SEPSIS","Sepsis")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A SEPSIS DE ORIGEN INTRA ABDOMINAL","Sepsis")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Sepsis no especificado","Sepsis")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Septecemia","Sepsis")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Septicemia","Sepsis")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Septicemia no especificada","Sepsis")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Septicemia no Especificada","Sepsis")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Septicemia no especificada","Sepsis")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A Shoc Septico","Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A SHOCK SEPTICO","Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"A SHOCK HIPOVOLEMICO","Choque hipovolemico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"ACCIDENTE CEREBROVASCULAR HEMORR�GICO","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Hemorr�gico Izquierdo","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Hemorr�gico Severo","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Hemorr�jico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente cerebrovascular Hemor�gico Paro Cardiorrespiratorio","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Hermorragico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Hipertension Aterial Nuemonia","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular I","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular I ","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular III IV","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente cerebrovascular Infarto agudo de miocardio","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Isga�nico extarso","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Isgramico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente cerebrovascular isquemico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente cerebrovascular Isquemico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular isquemico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Isquemico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"ACCIDENTE CEREBROVASCULAR ISQUEMICO","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Isquemico Agudo","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Isquemico Recidivante","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente cerebrovascular isqu�mico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular isqu�mico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Isqu�mico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"ACCIDENTE CEREBROVASCULAR ISQU�MICO","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular isqu�mico extenso","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Isqu�mico Izquierdo","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular IX","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"ACCIDENTE CEREBROVASCULAR IX","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente cerebrovascular izquemico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Izquemico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente cerebrovascular izquierdo","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Masiva","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular masivo","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Masivo","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"ACCIDENTE CEREBROVASCULAR MASIVO","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente cerebrovascular metabolico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Multifocal Isquemia Card�aca","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular m�s Hipertensi�n","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente cerebrovascular no especificado","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular no especificado","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular no Especificado","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular por mal Formaci�n Congenita","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente cerebrovascular reincidente","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Reincidente","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Reincidente Fulminante","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Reinsidente","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"ACCIDENTE CEREBROVASCULAR RS","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular secundaria a Hipertensi�n","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Secundario a Hipertensi�n Arterial","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente cerebrovascular Segundario a H+A","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente CEREBROVASCULAR SEVERO","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular tipo Hemorr�gico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Trambotico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Tromboembolico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente cerebrovascular tromboemb�lico extenso","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Trombotico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Tromb�nico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Tromb�tico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovascular Tronbotico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovasculas","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovasular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovencular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerebrovscular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerecro V�scular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Ceredro Vascular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cereoro  Vascular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cererbro Vascular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente cerero Vascular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerevascular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerobro Vascular Hemorr�gico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerobro Vascular Masivo","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerobrovascular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerrebrovascular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Cerro Vascular Hemorragico","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Conepro Vascular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Corobrovascular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"ACCIDENTE CREBRO VASCULAR","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Crebro Vascular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Crebro Vasculasr","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente Crebrovascular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente de cerebro Vascular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Accidente de Cerebro Vascular","Accidente Cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Infarto Miocardio", "Infarto Agudo al Miocardio")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Infarto agudo del miocardio","Infarto Agudo al Miocardio")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Broncoaspiraci�n","Broncoaspiracion")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Infarto Agudo al miocardio","Infarto Agudo al Miocardio")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Intoxicaci�n Alcoh�lica","Intoxicacion alcoholica")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"No Determinado","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Muerte Subita","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Asfixia por Suspensi�n","Asfixia por supresion")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Ulcera Gastrica","Ulcera Gastrica")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Choque Septico Pulmonar","Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"SENECTUD","Senectud")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Laceraci�n Cardiaca","Laceracion Cardiaca")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Choque Cardiog�nico","Choque cardiogenico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Paro respiratorio","Paro respiratorio")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Sindrome Diarreico Agudo","Sindrome diarreico agudo")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Neumonia Nosocomial","Neumonia nosocomial")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Tromboembolia Pulmonar","Tromboembolia pulmonar")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Sepsis Neonatal","Sepsis")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Neumonia Bilateral","Neumonia bilateral")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"En Estudio","DESCONOCIDA")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Infecci�n Intestinal","Infeccion intestinal no especificada")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Insuficiencia Cardiaca Congestiva","Insuficiencia cardiaca congestiva")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Shock Cardiogenico","Choque cardiogenico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Septicemia","Sepsis")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Hemorragia Pulmonar","Hemorragia pulmonar")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Fallo multiorganico","Fallo multiorganico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Diabetes Mellitus Mellitus Descompensada","Diabetes Mellitus")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Infarto del Miocardio","Infarto Agudo al Miocardio")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Enfermedad Cerebro Vascular","Evento cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Hemorragia Cerebral","Evento cerebrovascular")
all_data$CAUSA1<-str_replace(all_data$CAUSA1,"Estado de choque septico","Choque S�ptico")
all_data$CAUSA1<-str_replace(all_data$CAUSA1, "Estado deChoque Septico", "Choque S�ptico")


all_data

write.csv(all_data,"all_data.csv", row.names = FALSE)

